# Generated by Django 4.2 on 2023-04-16 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de usuario')),
                ('Nombre', models.CharField(max_length=50, verbose_name='Nombre del usuario')),
                ('Apellido', models.CharField(max_length=50, verbose_name='Apellido del usuario')),
                ('Correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('Direccion', models.CharField(max_length=50, verbose_name='Direccion del usuario')),
                ('Contraseña', models.CharField(max_length=50, verbose_name='Contraseña')),
            ],
        ),
    ]
